services:
  mongodb:
    image: mongo:8
    container_name: online-survey-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - online-survey-mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: online-survey-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  online-survey-mongo-data:
